// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZPzFN-yl2R9XIue0E0MAqRHh9-9I1bZk',
    appId: '1:488039957129:web:f2e34a495cbfdcd1e13c58',
    messagingSenderId: '488039957129',
    projectId: 'chatbox-a9a34',
    authDomain: 'chatbox-a9a34.firebaseapp.com',
    storageBucket: 'chatbox-a9a34.firebasestorage.app',
    measurementId: 'G-DVSLHLGR0B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiuPzJ5KHGZo6mrtDrZXkdwLbqOh00A8A',
    appId: '1:488039957129:android:36fe5ccb3f744414e13c58',
    messagingSenderId: '488039957129',
    projectId: 'chatbox-a9a34',
    storageBucket: 'chatbox-a9a34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXeE1FlPIl8aoLDknVC7d1cM4QI3cvrEE',
    appId: '1:488039957129:ios:aad4572acfb33588e13c58',
    messagingSenderId: '488039957129',
    projectId: 'chatbox-a9a34',
    storageBucket: 'chatbox-a9a34.firebasestorage.app',
    androidClientId: '488039957129-bip0s2i0cp8ds44i97e9fcg1623dl1qn.apps.googleusercontent.com',
    iosClientId: '488039957129-tku593kffsk2hk1c53kntdb7ns3hv9m3.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatbox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXeE1FlPIl8aoLDknVC7d1cM4QI3cvrEE',
    appId: '1:488039957129:ios:aad4572acfb33588e13c58',
    messagingSenderId: '488039957129',
    projectId: 'chatbox-a9a34',
    storageBucket: 'chatbox-a9a34.firebasestorage.app',
    androidClientId: '488039957129-bip0s2i0cp8ds44i97e9fcg1623dl1qn.apps.googleusercontent.com',
    iosClientId: '488039957129-tku593kffsk2hk1c53kntdb7ns3hv9m3.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatbox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_-VFVFaCe08oF-krPLMi_W5Npa5YzbqY',
    appId: '1:488039957129:web:15d56096ac66e68ae13c58',
    messagingSenderId: '488039957129',
    projectId: 'chatbox-a9a34',
    authDomain: 'chatbox-a9a34.firebaseapp.com',
    storageBucket: 'chatbox-a9a34.firebasestorage.app',
    measurementId: 'G-XVV3QL5SZG',
  );
}
